name: white_label_customer_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.1
  firebase_auth: ^4.19.3
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  flutter_svg_provider: any
  flutter_slidable: ^3.1.0
  shimmer: ^2.0.0 
  flutter_stripe: ^10.1.1
  http: ^0.13.5
  logging: ^1.0.2
  cloud_functions: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/placeholder_image.png
