name: white_label_customer_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  cloud_functions: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  flutter_svg_provider: ^1.0.7
  flutter_slidable: ^3.1.0
  shimmer: ^3.0.0
  flutter_stripe: ^10.1.1
  http: ^1.2.1
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/placeholder_image.png
